title: "Resource Manager Example Functions"
description: "Resource Manager로 Function Application을 생성하고 Function을 배포하고 테스트하는 예제입니다."
schemaVersion: 1.0.0
version: "20240724"
locale: "en"

variableGroups:
  - title: "Hidden"
    visible: false
    variables:
      - api_fingerprint
      - current_user_ocid
      - tenancy_ocid
      - region
  - title: "Basic Configuration"
    variables:
      - name_prefix
      - application_display_name
      - compartment_ocid
      - availability_domain
  - title: "Function Configuration"
    variables:
    - function_display_name
    - function_memory_in_mbs
    - function_timeout_in_seconds
    - use_concurrency
    - provisioned_concurrency_strategy
    - provisioned_concurrency_count
    - function_trace_enable
  - title: "OCIR Configuration"
    variables:
    - ocir_namespace
    - ocir_user_name
    - ocir_user_password
    - ocir_docker_repository
  - title: "Function Image Configuration"
    variables:
    - function_image_name
    - function_image_tag
    - function_image_repo
variables:
  api_fingerprint:
    required: false
    visible: false
  current_user_ocid:
    title: User
    type: ocid
    required: true
  tenancy_ocid:
    title: Tenancy
    type: oci:identity:compartment:id
    required: true
  compartment_ocid:
    title: Compartment
    description: The default compartment for created resources.
    type: oci:identity:compartment:id
    required: true
  region:
    required: true
    title: Region
    type: oci:identity:region:name
  availability_domain:
    title: Availability domain
    type: oci:identity:availabilitydomain:name
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}
  freeform_tags:
    type: string
    visible: false
    required: false
  public_subnet_ocid:
    type: string
    visible: false
    required: false
  name_prefix:
    type: string
    title: Name Prefix
    required: true
    description: "Functions Application과 Function 이름의 앞 Prefix를 설정합니다. Prefix는 문자 혹은 숫자여야 하며, 첫 글자는 문자여야 합니다." 
    default: "myocitf"
  application_display_name:
    type: string
    title: Application Name
    required: true
    description: "Functions Application 이름으로 Prefix-{Application Name} 형태로 사용됩니다." 
    default: "nodeapp"
  function_display_name:
    type: string
    title: Function Display Name
    description: "Functions Application 이름으로 Prefix-{Application Name} 형태로 사용됩니다." 
    required: true
    default: "hello-nodejs"
  function_memory_in_mbs:
    title: Memory (mbs)
    description: 
    type: enum
    required: true
    enum:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    default: 256
  function_timeout_in_seconds:
    title: Timeout (sec)
    description:
    type: integer
    required: true
    minimum: 1
    maximum: 300
    default: 120
  use_concurrency:
    title: Use Concurrency
    description:
    type: boolean
    default: false
  provisioned_concurrency_strategy:
    title: Concurrency Strategy
    description: 
    type: emum
    required: false
    enum:
    - NONE
    - CONSTANT
    default: NONE
    visible:
      and:
        - use_concurrency
  provisioned_concurrency_count:
    title: Concurrency Count
    description: 
    type: integer
    required: false
    default: 0
    minimum: 0
    maximum: 40
    multipleof: 1
    visible:
      and:
        - use_concurrency
  function_trace_enable:
    title: Trace
    description:
    type: boolean
    default: false
  ocir_namespace:
    type: string
    title: OCIR Namespace
    description:
    required: true
    default: "axlpeslmb1ng"
  ocir_user_name:
    type: string
    title: OCIR User Name
    description:
    required: true
    default: "donghu.kim@oracle.com"
  ocir_user_password:
    type: string
    title: password
    description:
    required: true
    default: "LXwtE9D[GT[#>shnvxi["
  ocir_docker_repository:
    type: string
    title: OCIR Docker Repository
    description:
    required: true
    default: "icn.ocir.io"
  function_image_name:
    type: string
    title: Function Image Name
    description:
    required: true
    default: "hello-nodejs"
  function_image_tag:
    type: string
    title: Function Image Name
    description:
    required: true
    default: "0.0.1"
  function_image_repo:
    type: string
    title: Function Image Repository
    description:
    required: true
    default: "my-functions-repo"